"""empty message

Revision ID: 3d2771414f50
Revises: 5d212048678a
Create Date: 2023-07-04 09:55:04.498050

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3d2771414f50'
down_revision = '5d212048678a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('verify_time1',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('final_time1',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('final_time1',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('verify_time1',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###
