"""empty message

Revision ID: 4ae3c95cc411
Revises: 222799e076ba
Create Date: 2023-06-08 16:28:14.251636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ae3c95cc411'
down_revision = '222799e076ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_list', schema=None) as batch_op:
        batch_op.drop_index('item')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_list', schema=None) as batch_op:
        batch_op.create_index('item', ['item'], unique=False)

    # ### end Alembic commands ###
