"""empty message

Revision ID: 5d212048678a
Revises: a917c7920eda
Create Date: 2023-07-04 09:48:33.837039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d212048678a'
down_revision = 'a917c7920eda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verify_time1', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('final_time1', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('final_time1')
        batch_op.drop_column('verify_time1')

    # ### end Alembic commands ###
