"""empty message

Revision ID: 78a9a5b56c29
Revises: f7a3e26270ea
Create Date: 2023-06-08 15:21:30.918826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78a9a5b56c29'
down_revision = 'f7a3e26270ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item1', sa.String(length=100), nullable=False),
    sa.Column('quantity1', sa.Integer(), nullable=False),
    sa.Column('price1', sa.Float(), nullable=False),
    sa.Column('item2', sa.String(length=100), nullable=False),
    sa.Column('quantity2', sa.Integer(), nullable=False),
    sa.Column('item3', sa.String(length=100), nullable=False),
    sa.Column('quantity3', sa.Integer(), nullable=False),
    sa.Column('price3', sa.Float(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_list')
    op.drop_table('order')
    # ### end Alembic commands ###
