"""empty message

Revision ID: 8946a244a3ae
Revises: 3a179390b88e
Create Date: 2023-07-03 14:33:48.658644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8946a244a3ae'
down_revision = '3a179390b88e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item1', sa.String(length=100), nullable=False),
    sa.Column('status1', sa.String(length=100), nullable=False),
    sa.Column('sentencing_time1', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
