"""empty message

Revision ID: a917c7920eda
Revises: 8946a244a3ae
Create Date: 2023-07-03 16:16:17.110170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a917c7920eda'
down_revision = '8946a244a3ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('laser_scanner1', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('laser_scanner1')

    # ### end Alembic commands ###
