"""empty message

Revision ID: f644c669b012
Revises: 6f88ca289774
Create Date: 2023-06-08 16:09:06.731569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f644c669b012'
down_revision = '6f88ca289774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_list', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['item'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_list', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
